apiVersion: v1
kind: Secret
metadata:
  name: pyxis-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "pyxis-agent.name" . }}
type: Opaque
stringData:
  api-key: {{ .Values.agent.apiKey | quote }}
