#!/usr/bin/env bash
# Pyxis Linux agent installer
# Usage (generated by the portal — do not edit manually):
#   curl -fsSL "https://YOUR_DOMAIN/install/linux?api_key=KEY&api_url=URL" | sudo bash
set -euo pipefail

PYXIS_API_KEY="${PYXIS_API_KEY:-__API_KEY__}"
PYXIS_API_URL="${PYXIS_API_URL:-__API_URL__}"
PYXIS_SOURCES="${PYXIS_SOURCES:-syslog}"
INSTALL_DIR="/opt/pyxis"
SERVICE_NAME="pyxis-agent"
SHIPPER_URL="${PYXIS_API_URL}/install/shipper.py"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[pyxis]${NC} $*"; }
warn()    { echo -e "${YELLOW}[pyxis]${NC} $*"; }
error()   { echo -e "${RED}[pyxis]${NC} $*" >&2; exit 1; }

# ── Checks ─────────────────────────────────────────────────────────────────

[[ $EUID -eq 0 ]] || error "Run as root (prefix with sudo)"
[[ "$PYXIS_API_KEY" == "__API_KEY__" ]] && error "PYXIS_API_KEY not set"
[[ "$PYXIS_API_URL" == "__API_URL__" ]] && error "PYXIS_API_URL not set"

# ── Dependencies ────────────────────────────────────────────────────────────

info "Checking dependencies..."
if ! command -v python3 &>/dev/null; then
    warn "python3 not found — installing..."
    if command -v apt-get &>/dev/null; then
        apt-get update -qq && apt-get install -y -qq python3
    elif command -v yum &>/dev/null; then
        yum install -y -q python3
    elif command -v dnf &>/dev/null; then
        dnf install -y -q python3
    else
        error "Cannot install python3 — please install it manually"
    fi
fi
info "python3 $(python3 --version)"

# ── Install agent ───────────────────────────────────────────────────────────

info "Installing to ${INSTALL_DIR}..."
mkdir -p "${INSTALL_DIR}"

info "Downloading shipper..."
curl -fsSL "${SHIPPER_URL}" -o "${INSTALL_DIR}/shipper.py"
chmod +x "${INSTALL_DIR}/shipper.py"

# Write env config
cat > "${INSTALL_DIR}/.env" <<EOF
PYXIS_API_KEY=${PYXIS_API_KEY}
PYXIS_API_URL=${PYXIS_API_URL}
PYXIS_NODE_NAME=$(hostname -f 2>/dev/null || hostname)
PYXIS_NODE_KIND=linux_host
PYXIS_SOURCES=${PYXIS_SOURCES}
PYXIS_BUFFER_DIR=/var/lib/pyxis/buffer
EOF
chmod 600 "${INSTALL_DIR}/.env"
mkdir -p /var/lib/pyxis/buffer

# ── Systemd service ─────────────────────────────────────────────────────────

info "Installing systemd service..."
cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=Pyxis log shipper
Documentation=https://pyxis.io
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
EnvironmentFile=${INSTALL_DIR}/.env
ExecStart=/usr/bin/python3 ${INSTALL_DIR}/shipper.py --sources \${PYXIS_SOURCES}
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=pyxis-agent

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now "${SERVICE_NAME}"

# ── Verify ──────────────────────────────────────────────────────────────────

sleep 2
if systemctl is-active --quiet "${SERVICE_NAME}"; then
    info "Agent is running ✓"
    info "View logs: journalctl -u ${SERVICE_NAME} -f"
    info "Status:    systemctl status ${SERVICE_NAME}"
else
    warn "Agent may not be running — check: journalctl -u ${SERVICE_NAME} -n 50"
fi

info "Done. Pyxis agent installed on $(hostname)"
